In [2]:
%matplotlib inline

In [3]:
from numpy.random import randn
import numpy as np
np.set_printoptions(precision=4, suppress = True)

In [4]:
# To create random number
data = randn(2,3)

data

array([[ 0.0428,  0.8578, -0.4282],
       [ 0.1908,  0.8551,  0.646 ]])

In [5]:
# Each variable multiplied by 10
data*10

array([[ 0.4279,  8.5782, -4.2817],
       [ 1.9084,  8.5513,  6.4599]])

In [6]:
data + data

array([[ 0.0856,  1.7156, -0.8563],
       [ 0.3817,  1.7103,  1.292 ]])

In [7]:
# To know shape of array
data.shape

(2, 3)

In [8]:
# To know type of array
data.dtype

dtype('float64')

In [9]:
# Creating array (One dimentional)
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)

In [10]:
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [11]:
#Creating Multidimentional Array (Matrix)
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)

In [12]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
# to check dimensions 2D
arr2.ndim

2

In [14]:
# For shape
arr2.shape

(2, 4)

In [15]:
arr2.dtype

dtype('int64')

In [16]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [17]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [18]:
# It’s not safe to assume that np.empty will return an array of all zeros. In
# many cases, as previously shown, it will return uninitialized garbage values.
np.empty((2,3,2))

array([[[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]]])

In [19]:
# "arange" is an array-valued version of the built-in Python 'range' function
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
# Some Array creation functions
# array - convert input data(list, tuple, array, or other sequence type) to ndarray
# asarray - convert input to ndarray, but don't if inputs is already in ndarray
# arange - like the built-in range but returns an ndarray instead of a list
# ones - produce an array of all 1's with the given shape and dtype
# ones_like - takes another array and produces a ones array of the same shape and dtype
# zeros, zeros_like - same as above but producing arrays of 0's
# empty, empty_like - Create new arrays by allocating new memory, but do not populate with any values like ones and zeros
# eye, identity - create a square N * N identity matrix

np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [21]:
np.identity(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [22]:
np.ones((8,2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [23]:
np.ones_like((4,5,6))

array([1, 1, 1])

In [24]:
abc = np.array([1, 2, 3, 4, 5])

In [25]:
abc.dtype

dtype('int64')

In [26]:
# np.float64 used to convert interger array into float array
cba = abc.astype(np.float64)

In [27]:
cba.dtype

dtype('float64')

In [28]:
# here we will convert float array into integer array by using np.int32
arr =np.array([3.7,-1.2,-2.6,12.9,5.5,10.1])

In [29]:
arr

array([  3.7,  -1.2,  -2.6,  12.9,   5.5,  10.1])

In [30]:
arr.astype(np.int32) # or also convert into int64

array([ 3, -1, -2, 12,  5, 10], dtype=int32)

In [31]:
# can convert numeric string ('64') in to float
numeric_string = np.array(['1.25','-9.6','42'])

In [32]:
numeric_string.astype(float) # it can also be work with np.float or float

array([  1.25,  -9.6 ,  42.  ])

In [33]:
# We can also use another array's dtype (data type) attribute
int_array = np.arange(10)

In [34]:
calibers = np.array([.22,.23,.45,.12]) 
# or calibers = np.array([.22,.23,.45,.12], dtype=np.float64)

In [35]:
int_array.astype(calibers.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [36]:
empty_uint32 = np.empty(8, dtype = 'u4')
empty_uint32

array([         0, 1072693248,          0, 1072693248,          0,
       1072693248,          0, 1072693248], dtype=uint32)

In [37]:
# Operations between Arrays and Scalar
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [38]:
arr * arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [39]:
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [40]:
1/arr

array([[ 1.    ,  0.5   ,  0.3333],
       [ 0.25  ,  0.2   ,  0.1667]])

In [41]:
arr ** 0.5 # for square root

array([[ 1.    ,  1.4142,  1.7321],
       [ 2.    ,  2.2361,  2.4495]])

In [42]:
# Basic Indexing and Slicing
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
arr[5] # want position 5 value.

5

In [44]:
arr[5:8] # In Python it will take first value but not last one so only 5,6 and 7

array([5, 6, 7])

In [45]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [46]:
arr_slice = arr[5:8] # Assign value to arr_slice at 5,6 and 7 location

In [47]:
arr_slice[1] = 12345 # Assign value 12345 at arr_slice 2nd position

In [48]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [49]:
arr_slice[:] = 64 # Assign 64 values to each arr_slice values
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [50]:
arr[5:8].copy

<function ndarray.copy>

In [51]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [52]:
a = arr[5:8].copy() # If need to explicitly copy the array
a

array([64, 64, 64])

In [53]:
# for multidimentional array (Martix)
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
arr2d[2] # to get whole row of that matrix

array([7, 8, 9])

In [55]:
arr2d[0][2] # for 0 means 1st row and 2 means 3rd column

3

In [56]:
arr2d[0,2] # same as above but in different form

3

In [57]:
# 3D array for 2 * 2 * 3 array
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d
# first 2 means first & second small 2*3 matrix
# second 2 means two rows
# third 3 means three columns

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [58]:
# arr3d[0] is a 2*3 array
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
# example of copy arrays
old_values = arr3d[0].copy()

In [60]:
arr3d[0] = 42 # assign 42 values to first 2*3 array
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [61]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [62]:
arr3d[1,0] # here second 2*3 matrix and it's first row

array([7, 8, 9])

In [63]:
# Indexing with slices
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [64]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
arr2d[:2] # it will take for first two rows (: means up to that value not that last one)


array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
arr2d[:2,1:] # here, up to second row and from second column

array([[2, 3],
       [5, 6]])

In [67]:
# some more slicing examples
arr2d[1, :2]

array([4, 5])

In [68]:
arr2d[2,:1]

array([7])

In [69]:
# : (colon) means to take entire axis
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [70]:
arr2d[:2, 1:] = 0


In [71]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [72]:
# Boolean Indexing
names = np.array(['Bob','Joe', 'Will', 'Joe', 'Joe'])
data = randn(7,4)

In [73]:
names

array(['Bob', 'Joe', 'Will', 'Joe', 'Joe'], 
      dtype='<U4')

In [74]:
data

array([[ 0.2146, -0.6184, -1.0093,  1.5796],
       [ 1.4062, -0.0082,  0.7688, -0.2521],
       [ 0.5604, -0.1703,  0.525 ,  0.3741],
       [ 1.7508, -1.2047, -0.3896,  0.675 ],
       [ 0.0069, -1.6069,  1.1135,  1.1209],
       [-0.3887, -0.9908, -0.0692,  0.8133],
       [-0.2031, -1.1684, -0.0297, -1.0571]])

In [75]:
# If we wanted to select all the rows with corresponding name "Bob"
names == "Bob"
# with this we can determine where "Bob" name is located.

array([ True, False, False, False, False], dtype=bool)

In [76]:
data[names == 'Bob']
# In this where the "Bob" name is that no. row will generate.

/home/vivek/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 7 but corresponding boolean dimension is 5
  """Entry point for launching an IPython kernel.


array([[ 0.2146, -0.6184, -1.0093,  1.5796]])

In [77]:
data[names == 'Joe']

/home/vivek/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 7 but corresponding boolean dimension is 5
  """Entry point for launching an IPython kernel.


array([[ 1.4062, -0.0082,  0.7688, -0.2521],
       [ 1.7508, -1.2047, -0.3896,  0.675 ],
       [ 0.0069, -1.6069,  1.1135,  1.1209]])

In [78]:
# This also slice particular row and will give outputs.
data [names == 'Bob',2:]

/home/vivek/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 7 but corresponding boolean dimension is 5
  


array([[-1.0093,  1.5796]])

In [79]:
# To select everything but 'Joe' we can use != or -(names == 'Joe')
names != 'Joe'

array([ True, False,  True, False, False], dtype=bool)

In [80]:
# Be careful for Using capitol letters in Names
data[-(names == 'Joe')]

/home/vivek/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning: numpy boolean negative, the `-` operator, is deprecated, use the `~` operator or the logical_not function instead.
  
/home/vivek/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 7 but corresponding boolean dimension is 5
  


array([[ 0.2146, -0.6184, -1.0093,  1.5796],
       [ 0.5604, -0.1703,  0.525 ,  0.3741]])

In [81]:
# To select two of the three names to combine multiple boolean conditions, 
# like arithmatic operations &(and) , |(or)
mask = (names == 'Bob') | (names == "Will") 

In [82]:
mask

array([ True, False,  True, False, False], dtype=bool)

In [83]:
data[mask]

/home/vivek/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 7 but corresponding boolean dimension is 5
  """Entry point for launching an IPython kernel.


array([[ 0.2146, -0.6184, -1.0093,  1.5796],
       [ 0.5604, -0.1703,  0.525 ,  0.3741]])

In [84]:
# To select all the negative value to be 0
data[data < 0] = 0
data

array([[ 0.2146,  0.    ,  0.    ,  1.5796],
       [ 1.4062,  0.    ,  0.7688,  0.    ],
       [ 0.5604,  0.    ,  0.525 ,  0.3741],
       [ 1.7508,  0.    ,  0.    ,  0.675 ],
       [ 0.0069,  0.    ,  1.1135,  1.1209],
       [ 0.    ,  0.    ,  0.    ,  0.8133],
       [ 0.    ,  0.    ,  0.    ,  0.    ]])

In [85]:
# Setting rows or column using 1D boolean array 
data[names != 'Joe'] = 7
data

/home/vivek/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 7 but corresponding boolean dimension is 5
  


array([[ 7.    ,  7.    ,  7.    ,  7.    ],
       [ 1.4062,  0.    ,  0.7688,  0.    ],
       [ 7.    ,  7.    ,  7.    ,  7.    ],
       [ 1.7508,  0.    ,  0.    ,  0.675 ],
       [ 0.0069,  0.    ,  1.1135,  1.1209],
       [ 0.    ,  0.    ,  0.    ,  0.8133],
       [ 0.    ,  0.    ,  0.    ,  0.    ]])

In [86]:
# Fancy Indexing
arr = np.empty((8,4))

In [87]:
for i in range(8):
    arr[i] = i

In [88]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [89]:
# To select out subset of the rows in a particular order, can simply pass list or ndarray of integers
arr[[4,3,0,6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [90]:
# Using negative indices select rows from the end
arr[[-1,-4,-8]]
# for negative it starts with 1.

array([[ 7.,  7.,  7.,  7.],
       [ 4.,  4.,  4.,  4.],
       [ 0.,  0.,  0.,  0.]])

In [91]:
# 
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [92]:
# Here we take first box for rows and second box for columns
# It means that (1,0) - 2nd row 1st column, (5,3) - 6th row 4th column etc.
arr[[1,5,7,2], [0,3,1,2]]

array([ 4, 23, 29, 10])

In [93]:
#To select square region in below, first box is for which rows we want
# After selecting rows, Second box is for all the rows and which colums we wanted 
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [94]:
# Another way is use np.ix_ function, converts two 1D integer array to an
# indexer that selects the square region
arr[np.ix_([1,5,7,2],[0,3,1,2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [95]:
# Transposing Arrays and Swapping Axes
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [96]:
# To find transpose of the matrix
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [97]:
# Will useful for multiplication of matrix and it's Transpose using np.dot function
np.dot(arr.T,arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [98]:
# same as above another example
arr = np.random.randn(6,3)
arr
# Also can use arr = randn(6,3)

array([[ 0.1478, -0.3808,  0.3623],
       [ 3.425 ,  0.1719, -1.0777],
       [-0.2816,  0.7921,  0.4716],
       [-0.6755,  0.1172, -0.434 ],
       [-0.6759,  0.7584, -0.2662],
       [ 0.6319,  1.0885, -1.4724]])

In [99]:
# to do matrix multiplication of this same matrix using np.dot function
np.dot(arr.T,arr)

array([[ 13.1441,   0.4055,  -4.2277],
       [  0.4055,   2.5758,  -1.8051],
       [ -4.2277,  -1.8051,   3.9423]])

In [100]:
# For higher dimensional arrays, transpose will accept ruple of axis numbers
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [101]:
# To get transpose of the 3D array
arr.transpose((1,0,2))
# Don't use arr.T for 3D array

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [102]:
# ndarray has the method "swapaxes" which takes a pair of axis numbers
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [103]:
# "swapaxes" similarly returns a view on the data without making a copy
arr.swapaxes(2,1) # same o/p will get by arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [104]:
# Universal Function: Fast Element-wise Array Function
arr = np.arange(10)
np.sqrt(arr)
# This will give square root answer elements-wise

array([ 0.    ,  1.    ,  1.4142,  1.7321,  2.    ,  2.2361,  2.4495,
        2.6458,  2.8284,  3.    ])

In [105]:
# This exp means e^ each element and their answer
np.exp(arr)

array([    1.    ,     2.7183,     7.3891,    20.0855,    54.5982,
         148.4132,   403.4288,  1096.6332,  2980.958 ,  8103.0839])

In [106]:
x = randn(8)
y = randn(8)

In [107]:
x

array([ 1.5953, -0.1425,  1.199 , -0.8528, -0.6088, -0.7566, -0.1123,
       -0.5035])

In [108]:
y

array([ 1.3153, -0.8823, -0.5992, -0.8064, -0.4492,  0.9854, -0.4276,
        0.8054])

In [109]:
# element wise maximum
np.maximum(x,y)

array([ 1.5953, -0.1425,  1.199 , -0.8064, -0.4492,  0.9854, -0.1123,
        0.8054])

In [110]:
arr = randn(7) *2
np.modf(arr)

(array([ 0.9523, -0.6533, -0.7917,  0.427 , -0.0287,  0.3443,  0.0445]),
 array([ 2., -0., -3.,  2., -2.,  1.,  0.]))

## listing of available ufunc (Universal functions)

- abs - compute the absolute value element-wise integer, floating point, or complex values
- fabs - faster alternative for non-complex valued data
- sqrt - compute the square root of each element. same as arr ^2 0.5
- square - compute square of each element. same as arr ^2 2
- exp - compute exponent e^x of each element
- log,log10, log2,log1p - Natural logarithm (base e), log base 10, log base 2, and log(1 + x), respectively
- sign - Compute the sign of each element: 1 (positive), 0 (zero), or -1 (negative)
- ceil - Compute the ceiling of each element, i.e. the smallest integer greater than or equal to each element
- floor - Compute the floor of each element, i.e. the largest integer less than or equal to each element
- rint - Round elements to the nearest integer,preserving the dtype
- modf - return fractional and integral parts of array as separate array
- isnan -return boolean array indicating whether each value is Nan (Not-a-Number)
- isfinite, isinf - return boolean array indicating whether each element is finite(non-inf,non-NaN) or infinite, respectively
- cos,cosh,sin,sinh,tan,tanh - regular and hyperbolic trigonometric functions
- arccos,arccosh,arcsin,arcsinh,arctan,arctanh - Inverse trigonometric functions

## Binary universal functions

- add - Add corresponding elements in array
- substract - subtract elements in second array from first array
- multiply - Multiply array elements
- divide, floor_divide - divide or floor divide (reuncating the remainder)
- power - raise elements in first array to powers indicated in second array
- minimum, fmin - element wise minimum. fmin ignores NaN
- maximum, fmax - element wise maximum. fmax ignores NaN
- mod - element wise modulus ( remainder of divison)
- copysign - copy sign of values in second argument to values in first argument
- greater, greater_equal,less,less_equal,equal,not_equal - >,>=,<,<=,==,!=
- logical_and,logical_or,logical_xor-compute element wise truth value of logical operation.equivalent to infix operators &,|,^

In [111]:
# Data Processing Using Arrays- vectorized array operationd will oftern be one or more order of magnitude faster than pure python
# np.meshgrid function takes two 1D arrays and produce two 2D matrices
points = np.arange(-5,5,0.01) # 1000 equally spaced points

In [112]:
xs, ys = np.meshgrid(points,points)

In [113]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ..., 
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [114]:
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ..., 
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [115]:
import matplotlib.pyplot as plt
z = np.sqrt(xs ** 2 + ys ** 2)
z

array([[ 7.0711,  7.064 ,  7.0569, ...,  7.0499,  7.0569,  7.064 ],
       [ 7.064 ,  7.0569,  7.0499, ...,  7.0428,  7.0499,  7.0569],
       [ 7.0569,  7.0499,  7.0428, ...,  7.0357,  7.0428,  7.0499],
       ..., 
       [ 7.0499,  7.0428,  7.0357, ...,  7.0286,  7.0357,  7.0428],
       [ 7.0569,  7.0499,  7.0428, ...,  7.0357,  7.0428,  7.0499],
       [ 7.064 ,  7.0569,  7.0499, ...,  7.0428,  7.0499,  7.0569]])

In [116]:
# matplotlib function imshow to create an image plot a 2D array of function values
plt.imshow(z, cmap=plt.cm.gray); plt.colorbar()
plt.show()

In [117]:
# Expressing conditional logic as array operations
# Suppose we wanted to take a value from xarr whenever the corresponding value in
# cond is True otherwise take the value from yarr.
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])
cond = np.array([True,False,True,True,False])
result = np.where(cond,xarr,yarr)
result

array([ 1.1,  2.2,  1.3,  1.4,  2.5])

In [118]:
arr = randn(4,4)
arr

array([[ 0.0514, -0.0806, -1.5404,  0.1108],
       [ 0.3913,  3.5167, -0.1229,  0.298 ],
       [-0.2607, -1.7501,  0.4951, -0.2366],
       [-0.6828, -1.1749,  0.1752,  0.0737]])

In [119]:
# suppose we wanted to replace all positive value with 2 and all negative values with -2. This is vey easy to do with np.where
np.where(arr > 0, 2, -2)

array([[ 2, -2, -2,  2],
       [ 2,  2, -2,  2],
       [-2, -2,  2, -2],
       [-2, -2,  2,  2]])

In [120]:
np.where(arr > 0, 2, arr) # set only positive values to 2

array([[ 2.    , -0.0806, -1.5404,  2.    ],
       [ 2.    ,  2.    , -0.1229,  2.    ],
       [-0.2607, -1.7501,  2.    , -0.2366],
       [-0.6828, -1.1749,  2.    ,  2.    ]])

- where also can be used for some logic functions such as
- I have two boolean arrays, cond1 and cond2, and wish to assign a
- different value for each of the 4 possible pairs of boolean values
  
  result = [ ]
     for i in range(n):
    if cond1[i] and cond2[i]:
       result.append(0)
    elif cond1[i]:
       result.append(1)
    elif cond2[i]:
       result.append(2)
    else:

In [ ]:
### we can replace this long condition with below "where" expression (It won't execute)
np.where (cond1 & cond2, 0, 
          np.where(cond1, 1,
                   np.where(cond2,2,3)))
result = 1 * cond1 + 2*cond2 + 3*-(cond1 | cond2)

In [122]:
# Mathematical and Statistical Methods
arr = np.random.randn(5,4) # normally-distributed data
arr

array([[ 0.9652,  1.1181,  0.7496,  0.3314],
       [ 0.1717,  0.1617,  0.1514,  1.2006],
       [ 1.175 ,  0.1131, -0.1089,  1.989 ],
       [-1.3889, -0.1162, -0.6165, -0.2942],
       [-1.3361, -0.9116,  1.2755,  0.2725]])

In [123]:
arr.mean() #or np.mean(arr) would be same

0.24512024294700913

In [124]:
np.sum(arr) #or arr.sum() would be same

4.9024048589401827

In [125]:
# Functions like mean and sum take an optional axis argument which computes the statistic
# over the given axis, resulting in an array with one fewer dimension
arr.mean(axis=0) # axis=0 means mean(avg) of row values (diff rows) & axis=1 means mean(avg) of column values (diff columns)

array([-0.0826,  0.073 ,  0.2902,  0.6999])

In [126]:
arr.mean(axis=1)

array([ 0.7911,  0.4214,  0.7921, -0.6039, -0.1749])

In [127]:
arr.sum(0) # also can write without mentioning "axis" variable for rows

array([-0.4132,  0.3652,  1.4511,  3.4994])

In [128]:
arr.sum(1) # same as above for rows

array([ 3.1643,  1.6854,  3.1682, -2.4158, -0.6998])

In [129]:
arr = np.array([[0,1,2],[3,4,5],[6,7,8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [130]:
# numpy.cumsum - Return the cumulative sum of the elements along the given axis.
arr.cumsum(0) # row wise 

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [131]:
# numpy.cumprod - Return the cumulative product of the elements along the given axis.
arr.cumprod(1) # column wise

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

In [132]:
# Methods for boolean arrays
# Boolean values are coerced to 1(True) and 0(False)
arr = randn(100)
(arr>0).sum() # Number of positive values

48

In [133]:
# any - tests whether one or more values in an array is True
# all - checks if every value is True
bools = np.array([False, False, True, False])
bools.any()

True

In [134]:
bools.all() # Because every value is not true

False

In [135]:
# Sorting
arr = randn(8)
arr

array([-1.0076,  0.5816, -0.1033,  0.1832, -0.8089, -0.7938,  0.8545,
        0.1755])

In [136]:
arr.sort()
arr

array([-1.0076, -0.8089, -0.7938, -0.1033,  0.1755,  0.1832,  0.5816,
        0.8545])

In [137]:
# for multidimentions array for sorting
arr = randn(5,3)
arr

array([[ 0.1948, -0.2709, -1.5272],
       [ 1.3742,  0.1328,  0.0135],
       [-0.8145, -0.0772,  0.248 ],
       [ 0.8348,  0.7586, -1.0606],
       [-0.1041,  0.4789,  0.4728]])

In [138]:
arr.sort(1) # sorting on only for row axis(1)
arr

array([[-1.5272, -0.2709,  0.1948],
       [ 0.0135,  0.1328,  1.3742],
       [-0.8145, -0.0772,  0.248 ],
       [-1.0606,  0.7586,  0.8348],
       [-0.1041,  0.4728,  0.4789]])

In [139]:
arr.sort(0) # sorting according column axis (0)
arr

array([[-1.5272, -0.2709,  0.1948],
       [-1.0606, -0.0772,  0.248 ],
       [-0.8145,  0.1328,  0.4789],
       [-0.1041,  0.4728,  0.8348],
       [ 0.0135,  0.7586,  1.3742]])

In [140]:
# To compute the quantiles of an array is to sort it and select the value at a partucular rank
large_arr = randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))] #5% quantile

-1.5758671590905045

In [141]:
# Unique and other set logic (np.unique)
names = np.array(['Bob','Joe','Will', 'Bob','Will','Joe','Joe'])
np.unique(names) # wiil give names which are common in alphabatical order
# by using pure python -- sorted(set(names))

array(['Bob', 'Joe', 'Will'], 
      dtype='<U4')

In [142]:
ints = np.array([3,3,2,5,4,1,2,2,5,1,3,4,5,1,2,1])
np.unique(ints)

array([1, 2, 3, 4, 5])

In [143]:
# np.in1d tests membership of the values in one array in another and reurning a boolean array
values = np.array([6,0,0,2,5,1,7,4,5,2,1,4,3])
np.in1d(values,[2,3,5])

array([False, False, False,  True,  True, False, False, False,  True,
        True, False, False,  True], dtype=bool)

In [144]:
# File Input and Outtheput with Arrays
arr = np.arange(10)
np.save('some_array', arr)


In [145]:
# If the file path doesn't already end in ".npy" the extension will be appended. and can be load by np.load
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [146]:
# Can save multiple arrays ina zip archive using np.savez and passing the arrays as keyword arguments.
brr = np.arange(15)
np.savez('array_archive.npz', a=arr, b=brr)

In [147]:
# To load .npz file, get back a dict-like object which loads the individual arrays lazily.
arch = np.load('array_archive.npz')
arch['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [148]:
# Linear Algebra
# for .(dot) product
x = np.array([[1.,2.,3.],[4.,5.,6.]])
y = np.array([[6.,23.],[-1,7],[8,9]])

In [149]:
x.dot(y) # equivalently np.dot(x,y)


array([[  28.,   64.],
       [  67.,  181.]])

In [150]:
np.dot(x, np.ones(3))

array([  6.,  15.])

In [151]:
# numpy.linalg has a standard set of matrix decompositions and things like inverse and determinant.
from numpy.linalg import inv, qr
X = randn(5,5)
mat = X.T.dot(X)
inv(mat)

array([[ 4.3139,  1.8906,  2.1876,  0.9019,  3.0556],
       [ 1.8906,  1.0896,  1.2854,  0.2793,  1.2822],
       [ 2.1876,  1.2854,  2.5211, -0.6479,  1.9758],
       [ 0.9019,  0.2793, -0.6479,  1.3808,  0.0107],
       [ 3.0556,  1.2822,  1.9758,  0.0107,  2.8263]])

In [152]:
mat.dot(inv(mat))  # multiplication of matrix and it's inverse

array([[ 1.,  0., -0.,  0.,  0.],
       [ 0.,  1., -0.,  0.,  0.],
       [-0., -0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0., -0.,  1.]])

In [153]:
q, r = qr(mat)
r
# q- orthonormal and r - upper triangle

array([[-9.6711,  0.0576,  5.7582,  9.3363,  6.5251],
       [ 0.    , -9.7552,  6.8774,  5.4052, -0.4346],
       [ 0.    ,  0.    , -1.3587, -0.7657,  1.1851],
       [ 0.    ,  0.    ,  0.    , -0.5713,  0.0469],
       [ 0.    ,  0.    ,  0.    ,  0.    ,  0.2091]])

In [154]:
q

array([[-0.6552,  0.1497, -0.0418, -0.3719,  0.6389],
       [ 0.1549, -0.8366, -0.4409, -0.0994,  0.2681],
       [ 0.2778,  0.4386, -0.5878,  0.4629,  0.4131],
       [ 0.5236,  0.278 , -0.1644, -0.7884,  0.0022],
       [ 0.4419, -0.09  ,  0.6568,  0.1265,  0.591 ]])

In [155]:
# Random number Generations(numpy.random)
samples = np.random.normal(size=(4,4))
samples

array([[-0.5612,  1.0761, -0.3133, -2.4292],
       [ 0.6199,  0.4473,  0.2335,  0.9954],
       [ 2.2928,  1.2109, -1.5245,  0.308 ],
       [-1.78  , -0.182 ,  0.7717,  0.5862]])

In [156]:
# A simple random walk
nsteps = 1000
draws = np.random.randint(0,2,size = nsteps)
steps = np.where(draws > 0,1,-1)
walk = steps.cumsum()

In [157]:
walk.min()

-30

In [158]:
walk.max()

22

In [159]:
# random walk to get at least 10 steps away from the origin 0 in either direction. np.abs(walk) >= 10 gives us a boolean array
# indicating where the walk has reached or exceeded 10, but we want the index of the first 10 or -10.
(np.abs(walk) >= 10).argmax()

93